name: nodelint

on:
  workflow_call:
    inputs:
      node-version:
        description: 'The Node.js version to use'
        required: false
        type: string
        default: 'auto'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run ESLint (Check for Errors)
      run: npx eslint .

    - name: Run Prettier (Auto-Fix)
      run: npx prettier --write .

    - name: Commit changes if Prettier fixed issues
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto-fix code formatting via Prettier" || echo "No changes to commit"
      continue-on-error: true
